services:
  app:
    build: .
    container_name: image_hosting_app
    ports:
      - "8000:8000"
    volumes:
      - images_volume:/app/images
      - logs_volume:/app/logs
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: image_hosting_nginx
    ports:
      - "8080:8080"
    volumes:
      - images_volume:/app/images:ro
      - ./static:/app/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app_network

volumes:
  images_volume:
    driver: local
  logs_volume:
    driver: local
  nginx_logs:
    driver: local

networks:
  app_network:
    driver: bridge